#! /bin/bash
# Copyright 2020 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
set -ex

PATH=${PATH}:${APPDIR}/bin
PATH=${PATH}:${APPDIR}/xournal
export PATH=${PATH}

LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/lib64
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/xournal
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}

XDG_DATA_DIRS=${XDG_DATA_DIRS}:${APPDIR}/share
export XDG_DATA_DIRS=${XDG_DATA_DIRS}

GDK_PIXBUF_MODULEDIR=${APPDIR}/lib64/gdk-pixbuf-2.0/2.10.0/loaders
export GDK_PIXBUF_MODULEDIR=${GDK_PIXBUF_MODULEDIR}

mkdir --parents ${HOME}/.config/xournal/gdk-pixbuf-2.0/2.10.0
GDK_PIXBUF_MODULE_FILE=${HOME}/.config/xournal/gdk-pixbuf-2.0/2.10.0/loaders.cache
export GDK_PIXBUF_MODULE_FILE=${GDK_PIXBUF_MODULE_FILE}

${APPDIR}/lib64/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > ${GDK_PIXBUF_MODULE_FILE}


${APPDIR}/xournal/xournalpp "$@"
